In [4]:
import numpy as np
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [5]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [8]:
#Get Specific element [r, c]
a[0,5]

6

In [9]:
#Gte a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [10]:
#Get a specific column
a[:,2]

array([ 3, 10])

In [11]:
#Startingindex:Endindex:stepsize
a[0, 1:6:2]

array([2, 4, 6])

In [12]:
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [13]:
#If i wanna replace 2nd column by 5 or by 1 , 2
a[:,2] = 5 #[1,2]
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


3-D Example

In [14]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [15]:
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [16]:
#Get specific element (work outside in)
b[0,1,1]

4

In [17]:
# Replace
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [18]:
b[:,1,:] = [[9,9],[8,8]]

In [19]:
print (b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]
