In [1]:
import numpy as np

In [9]:
a = np.array([1,2,3],dtype='int16')

In [10]:
print (a)

[1 2 3]


In [11]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [12]:
#Get dimensions
a.ndim

1

In [13]:
b.shape

(2, 3)

In [14]:
#Get Type
a.dtype

dtype('int16')

In [15]:
#Get size
a.itemsize

2

In [16]:
#Get Total Size 
a.size * a.itemsize

6

In [17]:
a.nbytes

6