Initializing Different Types of Arrays

In [2]:
# All 0s matrix
import numpy as np
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [ ]:
#For all ones we use np.ones

In [5]:
# For any other number 
np.full((2,3),99)

array([[99, 99, 99],
       [99, 99, 99]])

In [8]:
#Any other number(full_like) 
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [9]:
#Random decimal numbers
np.random.rand(4,2)

array([[0.25965625, 0.73717635],
       [0.42738594, 0.38256874],
       [0.8948999 , 0.88253211],
       [0.25112064, 0.47729838]])

In [10]:
np.random.random_sample(a.shape)

array([[0.42967495, 0.75942147, 0.78189231, 0.6297741 , 0.76157441,
        0.12264017, 0.16979754],
       [0.47030706, 0.39191069, 0.48761847, 0.38935004, 0.96594264,
        0.15154311, 0.56627214]])

In [12]:
#Random Integer Values
np.random.randint(4,7, size=(3,3))#random nos. between 4 & 7

array([[5, 5, 4],
       [6, 5, 4],
       [4, 4, 6]])

In [13]:
#The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
#Repeat an array
arr = np.array([[1,2,3]])

In [17]:
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [23]:
b = np.ones((5,5))
print(b)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

b[1:4,1:4] = z
print(b)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be carefull when copying array!!!

In [24]:
a = np.array([1,2,3])
b = a
print(b)

[1 2 3]


In [26]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(b)
print(a)# a(s) value also changed

[100   2   3]
[100   2   3]


In [27]:
 a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(b)
print(a)

[100   2   3]
[1 2 3]


### Mathematics

In [29]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [30]:
a+2

array([3, 4, 5, 6])

In [31]:
a-2

array([-1,  0,  1,  2])

In [32]:
a*2

array([2, 4, 6, 8])

In [33]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [34]:
b = np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [35]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [36]:
#Take the sin
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

###  Linear Algebra

In [39]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)#for multiplication of different dimension of matrices

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [42]:
#Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

#### Statistics

In [ ]:
stats = np.array([[1,2,3],[4,5,6]])
stats

In [45]:
np.min(stats)

1

In [46]:
np.max(stats)

6

In [47]:
np.sum(stats, axis=0)

array([5, 7, 9])

### Reorganizing Array

In [52]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [53]:
#Vertically Stacking Arrays 
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [55]:
#Horizontal Stacking Arrays 
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Load Data from file 

In [ ]:
filedata = np.genfromtxt('nameofthefile', delimiter = ',')
filedata = filedata.astype('int32')
filedata

In [ ]:
filedata[filedata>50] 

In [59]:
#You can index with a list in NumPy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])